apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mario-frontend
  template:
    metadata:
      labels:
        app: mario-frontend
    spec:
      containers:
      - name: mario-frontend
        image: maharshi369/mario_frontend
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mario-frontend
spec:
  selector:
    app: mario-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort

