apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mario-backend
  template:
    metadata:
      labels:
        app: mario-backend
    spec:
      containers:
      - name: mario-backend
        image: maharshi369/mario_backend
        ports:
        - containerPort: 8081
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DB_NAME
          value: "mario"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mario-backend
spec:
  selector:
    app: mario-backend
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: NodePort

