apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mario-backend
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
