apiVersion: v1
kind: LimitRange
metadata:
  name: mydiningresourcelimit
spec:
  limits:
  - type: Container
    max:
      cpu: "2000m"
      memory: "2Gi"
    min:
      cpu: "500m"
      memory: "500Mi"
    default:
      cpu: "500m"
      memory: "500Mi"
    defaultRequest:
      cpu: "500m"
      memory: "500Mi"

